FROM gliderlabs/alpine:3.1
CMD ["/bin/tcp-forward-proxy"]

ENV GOPATH /go
RUN apk-install go git mercurial
COPY . /go/src/github.com/mikroio/tcp-forward-proxy
RUN cd /go/src/github.com/mikroio/tcp-forward-proxy \
	&& go get \
	&& go build -ldflags "-X main.Version dev" -o /bin/tcp-forward-proxy

